config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}
  #devise_for :user, controllers: {
   #     sessions: 'user/sessions',
    #    registrations: 'user/registrations'
     # }
  resources :categories
  get 'archives/index'
  resources :entries
  root to: "entries#index"
end

app/models/entry.rb
class Entry < ApplicationRecord
	
  belongs_to :category
  belongs_to :user
  validates :calories, :proteins, :carbohydrates, :fats, :meal_type, :category_id, presence: true

	def day
		self.created_at.strftime("%b %e, %Y")
	end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.where("created_at >= ?", Date.today)
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = current_user.entries.build
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = current_user.entries.build(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:meal_type, :calories, :proteins, :carbohydrates, :fats, :category_id)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_with(model: entry, local: true) do |form| %>
  <% if entry.errors.any? %>
    
    <div class="message is-danger">
      <div class="message-header">
        <p><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</p>
      </div>
      
      <ul>
        <% entry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Food Item", class: "label" %>
    <%= form.text_field :meal_type, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :calories, class: "label" %>
    <%= form.number_field :calories, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :proteins, class: "label" %>
    <%= form.number_field :proteins, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :carbohydrates, class: "label" %>
    <%= form.number_field :carbohydrates, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :fats, class: "label" %>
    <%= form.number_field :fats, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :category, class: "label" %>
    <div class="select">
      <%= form.select :category_id, current_user.categories.collect {|u| [u.title, u.id]}%>
    </div>
  </div>
   
  <div class="columns is-centered">
    <div class="column is-half">
      <div class="actions">
        <%= form.submit class: "button is-success is-outlined is-fullwidth" %>
      </div>
        
      <br/><div class="buttons">
        <%= link_to "Back", root_path, class: "button is-link is-outlined is-fullwidth" %>
      </div>
    </div>
  </div>

<% end %>

app/views/entries/edit.html.erb
<div class="columns is-centered mt-6">
	<div class="column is-one-third">
		<h1 class="is-size-2 has-text-weight-bold md-3">Editing Entry</h1>
		<%= render 'form', entry: @entry %>
	</div>
</div>

app/views/entries/index.html.erb
<% content_for :title do %>
  Foodlog &ndash; <%= Time.zone.now.to_s(:nice_date) %>
<% end %>

  <div class="columns mt-6 is-centered">
    <% @entries.each do |entry| %>
      <% if entry.user == current_user %>
        <div class="column is-one-quarter">
          <div class="card">
            <header class="card-header">
              <p class="card-header-title"><%= entry.meal_type %> | <%= entry.category.title if entry.category.present? %></p>     
            </header>
          <div class="card-content">
            <div class="content">
              <p><span class="has-text-weight-bold"><%= entry.calories %></span> calories</p>
              <p><span class="has-text-weight-bold"><%= entry.proteins %></span> grams of protein</p>
              <p><span class="has-text-weight-bold"><%= entry.carbohydrates %></span> grams of carbohydrates</p>
              <p><span class="has-text-weight-bold"><%= entry.fats %></span> grams of fat</p>
              <p class="italic">Logged <%= time_ago_in_words(entry.created_at) %> ago</p>
            </div>
          </div>
          
          <div class="card-footer">  
            <%= link_to 'Show', entry, class: "card-footer-item" %>
            <%= link_to 'Edit', edit_entry_path(entry), class: "card-footer-item" %>
            <%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' }, class: "card-footer-item" %>
          </div>
        </div>
        </div> 
      <% end %>
    <% end %>
  </div>

  <div class="columns is-centered mt-6">
    <%= link_to "Create a new Entry", new_entry_path, class: "button is-link is-outlined mr-6 ml-4" %>
    <%= link_to "View all entries", archives_index_path, class: "button is-link is-outlined is-centered" %>
    <%= link_to "Create new category", new_category_path, class: "button is-link is-outlined is-centered mr-6 ml-6" %>
  </div>

app/views/entries/new.html.erb
<div class="columns is-centered mt-6">
	<div class="column is-one-third">
		<h1 class="is-size-2 has-text-weight-bold md-3">New  Entry</h1>
		<%= render 'form', entry: @entry %>
	</div>
</div>

app/views/entries/show.html.erb
<% content_for :title do %>
  <%= @entry.meal_type %> &ndash; <%= DateTime.now.to_s(:nice_date) %>
<% end %>

<div class="columns mt-6 is-centered">
  <div class="column is-one-third">
    <nav class="panel is-link">
      <p class="panel-heading">
        <%= @entry.meal_type %> :
        <%= @entry.category.title %>
      </p>

      <div class="panel-block">
        Calories: <%= @entry.calories %>
      </div>

      <div class="panel-block">
        Proteins: <%= @entry.proteins %>
      </div>

      <div class="panel-block">
        Carbohydrates: <%= @entry.carbohydrates %>
      </div>

      <div class="panel-block">
        Fats: <%= @entry.fats %>
      </div>
    </nav>
    
    <div class="columns is-mobile">
      <div class="buttons mb-2 mt-4">
        <%= link_to "Back", root_path, class: "button is-link is-light is-grey" %>
        <%= link_to "Edit", edit_entry_path(@entry), class: "button is-link is-light is-grey" %>
        <%= link_to "Delete", entry_path(@entry), method: :delete, data: { confirm: "Are you sure?" }, class: "button is-danger is-light is-grey" %>
      </div>
    </div>
  </div>
</div>